#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hola_mundo:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController:templateAction
  defaults:
    template: hola_mundo.twig.html